Repository milieuinfo/webcomponent-vl-ui-radio, pull requests merged in 2020-08, with the labels that each got.

#78 Introductie onderscheidende stijl van het label van een disabled radio element
  bamboo-specs/bamboo.yml
  dist/style.css
  dist/style.scss
  dist/vl-radio-all.min.js
  dist/vl-radio-group.min.js
  dist/vl-radio.min.js
  dist/vl-radio.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.scss
Labels: enhancement

#79 Update dependency @govflanders/vl-ui-util to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#80 Upgrade huisstijl versie 3.11.5
  demo/vl-radio-group.html
  demo/vl-radio.html
  dist/style.css
  dist/style.scss
  dist/vl-radio-group.js
  dist/vl-radio-group.src.js
  dist/vl-radio.js
  dist/vl-radio.min.js
  dist/vl-radio.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.scss
  src/vl-radio-group.js
  src/vl-radio.js
  test/unit/vl-radio.test.html
Labels: chore

#76 Mogelijk maken om te navigeren over vl-radio-group elementen via de tab toets
  demo/vl-radio-group.html
  package-lock.json
  package.json
  src/vl-radio-group.js
  src/vl-radio.js
  test/e2e/components/vl-radio-group.js
  test/e2e/components/vl-radio.js
  test/e2e/pages/vl-radio-group.page.js
  test/e2e/radio-group.test.js
  test/unit/vl-radio-group.test.html
  test/unit/vl-radio.test.html
Labels: bug
